name = "azure-workers-sdk"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
# Authentication - set via wrangler secret
# API_KEY = "your-secure-api-key"

# Email worker environment variables
# AZURE_COMMUNICATION_CONNECTION_STRING = "your-connection-string" 
# FROM_EMAIL = "noreply@yourdomain.com"

# Notifications worker environment variables  
# AZURE_NOTIFICATION_HUB_CONNECTION_STRING = "your-connection-string"
# AZURE_NOTIFICATION_HUB_NAME = "your-hub-name"

[env.production]
name = "azure-workers-sdk-prod"

[env.staging]
name = "azure-workers-sdk-staging"